= Related Work

This chapter will explore the existing knowledge and understanding on the effectiveness of design patterns, investigate guidelines and processes used to decide when to use which design pattern, as well as design patterns specifically for Rust. Finally, the research gap that this thesis aims to address will be identified.

== State of research on the effectiveness of design patterns

// mapping studies & literature reviews
A lack of consensus exists on the point of the effectiveness of design patterns. According to a literature survey from 2013, previous studies on the impact of design patterns yielded controversial results, with some studies reporting positive and others reporting negative outcomes @ali_comparative_2013. Moreover, the literature survey found that previous studies don't cover design patterns extensively enough, with not all of the @gof design patterns being covered, for example. A potential reason for this lack of consensus and controversial results could be the fact that design patterns come with tradeoffs @ampatzoglou_research_2013. While a design pattern might improve one aspect of quality, it might degrade another. Furthermore, there was a lack of objective data on design patterns as of 2012, and no "firm support for any of the claims" about design patterns, like improving reusability or reducing complexity universally @zhang_what_2012. In 2020, another systematic literature review found that there was no consensus about how design patterns impact maintainability @wedyan_impact_2020. While maintainability was found to be the most frequently assessed quality attribute, other attributes like change- and fault-proneness yielded contradictory results. In alignment with the previous studies, it points out that design pattern's effectiveness depends on the context it is used in. This shows that there is a lack of context-dependent assessment of design patterns' effects on software quality.

// measuring quality & dominance of java
When it comes to measuring source code quality, a mapping study from 2017 that summarizes and categorizes research on metrics found that most research on code metrics has been conducted in @oop languages @nunez-varela_source_2017. Specifically, most research was conducted in Java at 154 occurrences, followed by AspectJ and C++ at 30 and 24 occurrences, respectively. The study identifies fail safety, quality and complexity as most studied topics in object-oriented code. For procedural languages, the most studied metrics were @cyc and @loc. The study concludes that for new metrics, more secondary studies that evaluate them are necessary so practitioners and researchers can rely on them. This highlights a lack of research in non-object-oriented languages, particularly in languages other than Java.

// specific primary studies on design patterns
Primary sources that investigate the effects of design patterns show mixed evidence. As for positive evidence, a study from 2012 evaluates design patterns in the Java library JHotDraw by analyzing more than 300 revisions of it, using a probabilistic quality model @hegedus_myth_2012. The design pattern instances were retrieved from documentation in the code. It was found that all of the assessed quality characteristics improved with each introduced design pattern instance. However, the analyzed library JHotDraw can be seen as an exception, as it was co-developed by Erich Gamma for educational purposes @christensen_frameworks_2004, who is also one of the authors of the @gof patterns @gamma_design_1995, and therefore influenced the design of the software. An earlier study focuses on three selected @gof design patterns and demonstrated that they are effective at reducing high metric scores, thus causing less violations of alarm thresholds @huston_effects_2001. According to a more recent study from 2021, the use of design patterns significantly reduces complexity and improves maintainability @jun_evaluating_2021. The results are gathered through evaluating metrics such as @cyc and @mi, making use of the static code analysis tool SonarQube. Another study from 2017 found a positive effect of investigated design patterns on a system level @hussain_effect_2017 by using the @qmood @bansiya_hierarchical_2002. Because the latter two studies each only analyze three different design patterns, their findings are contextual and it is unclear whether other patterns yield similar improvements.

Other researchers developed a methodology to assess the impact of design patterns, and their results show that design patterns are not universally good or bad @ampatzoglou_methodology_2012. Still, the study found that patterns generally produce more extendible code, and that they should be preferably used for systems with high reusability and maintainability needs. Another study employed a qualitative evaluation method by questioning software engineers, and found that design patterns do not necessarily influence all quality attributes positively @khomh_design_2008. Based on this result, the researchers suggest that design patterns need to be used with caution, aligning with the findings of several other studies @ampatzoglou_methodology_2012 @ampatzoglou_research_2013 @ali_comparative_2013.

// documenting design patterns
When design patterns are used, it was found that documenting them with @uml diagrams or comments in the code improves correctness and ease of understanding @scanniello_documenting_2015. The researchers conducted the experiment with participants that had varying experience levels. Especially for developers with higher experience levels, documenting design patterns leads to better correctness of understanding the code.

== Guidelines for choosing the right design pattern

Numerous studies developed guidelines for when to use which design pattern, since it is a challenging task to choose a design pattern from the wide range available. In 2003, Kung et al. developed an expert system that suggests an appropriate design pattern based on the user's requirements @kung_expert_2003[p.291-292]. A rule-based knowledge base is used to perform a question-answer process with the user. Another approach based on a knowledge base was proposed by Palma et al. @palma_recommendation_2012 and also requires the user to answer questions about the design problem. Each question has an assigned weight and is mapped to appropriate patterns, so that a final ranking can be created. Another approach is based on defining the problem domain of a design pattern first @kim_software_2008. The study states that it is a difficult task to generalize the problem a pattern solves, and uses a methodology developed in previous work for formalizing pattern problem domains. As a result, the study presented an approach that enables developers to search a pattern that is applicable to a given problem model, including a prototype tool that transforms the original class diagram into a solution diagram that conforms the transformation specification. Yet it should be questioned whether this approach is practical, since it requires initial effort for formalizing the problem, and the problem domain for each design pattern.

Nevertheless, the underlying evidence for design pattern guidelines is mixed. A mapping study from 2012 concluded that there wasn't enough evidence and knowledge for creating a guideline on when to use which pattern @zhang_what_2012. At the time, the study identified a lack of empirical evidence for proving design patterns' effectiveness. In addition, the study concludes that design patterns don't help developers with low experience levels at making better design choices, and that applying patterns "blindly" is counterproductive.

== Existing design patterns for Rust

As of now, there is little data on the effectiveness of design patterns in Rust. Researchers recently developed a tool capable of analysis and extraction of bug fix patterns in Rust code, and used it to obtain the most common bug fix patterns from popular Rust projects @robatishirzad_study_2024. The study however doesn't describe design patterns in the classical sense on an architectural level, but rather single changes like modifying struct fields or `clone` calls.

Unofficial guidelines with design patterns applied to or specifically designed for Rust exist in online documentation. One such documentation is Refactoring Guru, which is a guide on @gof patterns with code examples for many implementation languages, including Rust @x:noauthor_design_nodate. Yet, it lacks verification of their effects on code quality. Furthermore, it excludes design patterns apart from @gof patterns that are Rust-specific. Another online documentation is maintained by the Rust open source community and lists patterns that are commonly used in Rust, including some of the @gof patterns and Rust-specific patterns based on its language features @x:noauthor_introduction_nodate. It is a practical guideline with examples, advantages and disadvantages for each pattern, but it doesn't study or verify the quality impacts of each pattern in detail.

There have been recent advances in investigating design patterns in Rust. Researchers identified that there is no equivalent catalogue like the object-oriented @gof patterns for @fp @crichton_typed_2023. The study extracts four recurring patterns from Rust code and verifies their positive impact on code correctness through case studies. While these are novel patterns that should be investigated more in future research, Rust as a multi-paradigm language might also support other design patterns that need to be investigated again in a Rust context.

== Research gap
In summary, it can be seen that research has been heavily focused on @gof patterns applied to Java code, and there is not much evidence on design patterns in the context of Rust, despite its growing relevance as shown in @introduction[Chapter]. It was pointed out that several literature surveys and mapping studies see the effectiveness of design patterns as controversial and context dependent, thereby further investigation is required.