#import "../pages/outline.typ": custom_caption

#show heading.where(level: 3): set heading(outlined: false)

= Case Study <casestudy>

This chapter will introduce the three use cases selected for the case study. The use cases will be selected from applications maintained by teams at OTTO that use Rust. Each use case will be explained briefly, guided by a diagram following the @bpmn. @bpmn is a standardized notation for business process flows, maintained by the Object Management Group, and can be seen as a common medium of communication between IT and business stakeholders @silver_bpmn_2011[p.3]. Each use case's relevance, current problems and proposed design pattern solution will be explained. Test code like unit and integration tests will not be part of the refactoring. Instead, they will be used as verification that the refactored code still works as intended. All use cases' status quo code can be found in @status-quo-digi[Appendix].

== Use case 1 <usecase1-case-study>

The first use case is the "Detailview" service maintained by FT9, which is a team at OTTO that uses Rust as main implementation language and is responsible for customer benefits on the store website. The Detailview service is responsible for creating view models that represent a small area on the product detail page and customer wishlist, which show a customer benefit (e.g. limited sale) that has been matched with the product and a slider for activating it. While the Detailview service itself is responsible for domain-specific logic only, requests are handled by another handler module that depends on the service. The @bpmn model in @bpmn1 illustrates how the service function creates the view model.

#figure(
  pad(x: 1cm, bottom: .5cm, image("../res/usecase1/bpmn.png")),
  caption: custom_caption([BPMN process model of the FT9 Detailview Service, selected as first use case, which is a single function with a long and linear sequence of operations that need to happen in order],
  [Use Case 1 - BPMN model of FT9 Detailview Service])
) <bpmn1>

When the service is called, the benefit IDs are first retrieved, and then used to collect the valid benefits. From those benefits, the one that will be displayed is selected. If there was no benefit found or the selected benefit is inactive, the service returns a `None` value early, depicted at the first `XOR`-gate in @bpmn1. Otherwise, the membership status of the customer in the "OTTO UP" bonus program gets checked. Next, it is checked whether the customer activated the benefit or not. If this isn't the case and the selected benefit needs to be activated automatically, it will be activated by the service. Otherwise, this step is skipped, which can be seen at the `XOR`-gate labeled "Needs to be activated?" in @bpmn1. Then the "Adjust" link, which is a link navigating mobile users to the OTTO app, gets created. Finally, the Detailview view model is built with the data retrieved so far and gets returned.

=== Relevance

The Detailview service can be seen as representative for many services used throughout the codebase at FT9. Services are commonly used to execute certain business logic, retrieve data and request other services. They are usually invoked by handlers, which return the result of the service to the requesting instance. Because this is a common architectural pattern at FT9, the Detailview service will be used to represent the use case *Service* at FT9.

=== Problems of the status quo

First of all, the main method in the service called `create_detailview_view_model` takes 7 parameters, which increases complexity @x:expert-a. The high amount of parameters causes difficulties in testing, as it requires many mocks and different combinations of values for covering all test cases @x:expert-a. This way, the number of test cases required quickly becomes large and hard to manage. Also, dependencies like `detailview_cache` make testing more difficult, as they need to be mocked or instantiated @x:expert-b. Even when dependencies like this are not needed for a specific step, every test of a condition or invariant requires mocking all dependencies @x:expert-d. Furthermore, because the function is defined on the struct `DetailviewService`, which requires multiple dependencies to construct, the function cannot be tested without mocking or setting up all those dependencies. Extensive test setup makes testing more difficult than it needs to be, so parameterized tests or property tests are currently not possible @x:expert-c. Overall, *C6 Testability* is seen as negatively in the current status quo.

Moreover, the function is notably long with 103 @loc, making it hard for the maintainer to understand the function and reason about isolated parts of the function. According to expert A, it is hard for the developer to understand the whole context of the function, which reduces *C4 Analysability* @x:expert-a. Experts B and D agree that the length of the function makes it difficult to grasp what operations are made and what the function actually does @x:expert-b,  @x:expert-d. Furthermore, the imperative programming style and high amount of conditional blocks and booleans makes it harder to read @x:expert-c.

Additionally, the function handles too much logic at once @x:expert-d and has too many responsibilities. This causes a mix of concerns like @io, business logic and logging @x:expert-a, @x:expert-b, @x:expert-c, violating the @srp and therefore degrading *C2 Modularity*. According to expert A, different steps like database access and filtering should take place in separate modules @x:expert-a. Another concern is that the function is tied too tightly to this use case, which makes it hard to reuse in other modules, according to experts A and B @x:expert-a, @x:expert-b. As a result, the *C3 Reusability* of the current code is degraded.

Also, navigating and changing the code becomes a major challenge, since the code lacks a clear isolated flow and logic is described as intertwined by expert C @x:expert-c, affecting *C5 Modifiability* negatively. This is confirmed by expert D, who states that making changes carries some risks because each change in the beginning of the function might affect everything downstream, increasing the chance of unintended consequences @x:expert-d.

Lastly, the function contains a range of if-conditions and invariants that are only checked during runtime, but not during compile time. This makes the function prone to errors like changing the order of some of the logic, which isn't detected until running the code @x:expert-c, @x:expert-d. Without explicit enforcements of function order, *C7 Faultlessness* is compromised.

=== Proposed solution <usecase1-solution>

This use case will be refactored using the _Typestate_ pattern, adhering to the suggestion of expert C to model the domain logic as a state machine @x:expert-c. The concept of typestate was first introduced by Strom and Yemeni, who define it as a refined version of the concept of types @strom_typestate_1986. Under the premise that syntactically incorrect programs and semantically incorrect programs are different, the goal of typestate is to detect operations that are semantically undefined, but syntactically correct and therefore remain unnoticed by the compiler. The authors state that typestate can be used to enforce invariants at compile time, so that the behaviour during runtime is constrained to allowed operations for that type. For example, take a type `File` that can be read and closed. Without typestates, the file might be closed, then read again, because the type system only defines which operations are possible, not which are allowed. When defining typestates, a program where a file is closed and subsequently read, can no longer compile. Closing the file will transition the program to a state where the read operation can no longer be performed.

The concept of typestates has been applied to practice through the design of a programming language with native typestate support called "Plaid" @aldrich_typestate-oriented_2009. The authors argue that while typestates are possible in Java, the complexity of generic types makes typestates difficult in practice. Rust's language features however make typestates idomatic and practical, mainly because of @adt:pl and the ownership concept. The first way of encoding a typeside is by using a generic field on a struct, which is a marker for the current typestate. The struct can contain data, but if the used struct is empty, it is a zero-cost abstraction that is optimized away by the compiler @x:noauthor_zero_nodate. The second way uses structs directly to represent each state: the structs define data of the state and allowed transitions can be implemented on them, whereas enums can be returned to indicate multiple possible resulting states. Enums are typically handled through a `match` statement, which is exhaustive by default, ensuring that all states are handled when the state is consumed. Furthermore, Rust's borrow checker enforces that when a state transition consumes `self`, it cannot be invoked multiple times, thereby preventing invalid operations. Aldrich et al. primarily focus on library and API design, whereas the application of typestate to isolated business logic remains largely unexplored @aldrich_typestate-oriented_2009, making this use case a novel problem domain.

Applying the typestate pattern will first of all address issues in *C7 Faultlessness* by defining the correct sequence of operations and encoding the assumed invariants in the type system. This way, errors like a wrong sequence of operations or wrong assumptions about the state of data will be prevented. The logic will be split down into state transitions, which explicitly define the input and output data. Therefore, *C5 Modifiability* will be addressed because changes can be narrowed down to the corresponding state and transition, which limits effects on the rest of the code. Since every state can theoretically be constructed from inside a unit test, *C6 Testability* will be enhanced significantly, because only the dependencies required for each specific state transition are needed. It will no longer be necessary to pass all dependencies to the single, large main function. The state's data will not contain external dependencies, making the construction of test values trivial.

A possible shortcoming is that the code necessary for defining states and possible transitions might cause conceptual overhead, as already described by Aldrich et al. @aldrich_typestate-oriented_2009. Thus, *C4 Analysability* might not be unanimously seen as improved after the refactoring. *C3 Reusability* is also not a main aspect of the refactoring, because more code outside of this use case needs to be investigated for finding reusable code parts.

== Use case 2

The second use case is chosen from FT9 as well. This use case is the "Tag Component" handler. Tags are small indicators seen on products and usually display discounts. The Tag Component handler directly handles requests from other teams who integrate the Tag on the shop's website. The handler returns a data object that is used to enrich the HTML template.

#figure(
  pad(y: .5cm, image("../res/usecase2/bpmn.png")),
  caption: custom_caption([BPMN process model of the FT9 Tag Handler, selected as second use case, which is a sequence of operations that depends on validated "Dreson" data and should otherwise fail],
  [Use Case 2 - BPMN model of FT9 Tag Component Handler])
) <bpmn2>

When a request is received, the handler first checks the emergency toggle, which can be used to quickly disable the handler in case there is an issue. After that, the input parameters "Target Context Dreson" and "Current Context Dreson" are read. A Dreson is a domain-specific expression used in the OTTO shop to describe product selections. It serves as a declarative selection rule that can reference individual products, sets of products, or entire product categories. Each of the Dresons, if it is present, is validated, and the handler returns an error if validation fails. This can be seen in and around the two "Validate Dreson" steps in @bpmn2, where invalid Dresons are depicted as error events. The rest of the handler is responsible for retrieving the benefit and returning it. If no benefit was found, an error is returned by the handler.

=== Relevance

The Tag Component handler represents *Handlers* in the code base of FT9. Handlers are invoked when their corresponding endpoint is called, and are responsible for handling incoming and outgoing data. Every endpoint requires a handler, and business logic is usually delegated to services, which are already represented through the first use case.

=== Problems of the status quo <usecase2-problems>

After the Dreson parameters are validated, the information that they are valid is not encoded in the type system. As a result, the strings might be redundantly re-validated later, or validation might be forgotten entirely without a notice from the compiler @x:expert-c. Due to the usage of raw strings, developers that extend the code can't make assumptions about the data's state @x:expert-d. These issues have a negative impact on *C7 Faultlessness*. Also, the parameters should semantically already be valid because they were passed through the struct `ValidatedParams`, so the Dreson values should be validated at construction as well instead of the beginning of the handler @x:expert-b, @x:expert-d. Besides the Dreson, expert B mentions that the "Sheet URL", which gets constructed in the end of the function, is based on raw strings instead of a builder pattern or typed logic, causing poor *C7 Faultlessness* and *C5 Modifiability* @x:expert-b.

Overall, the use of raw strings and a manual validation violates the principle "Parse, don't validate", which states that input values should parsed into a domain type as soon as possible. If parsing fails or the input is invalid, construction of the type fails entirely, which eliminates the need for a manual validation later @x:king_parse_2019.

Furthermore, the two Dreson input values have very similar structures for their validation, indicating code repetition, which also means low *C3 Reusability* @x:expert-a. The validation across different handlers can also be inconsistent because the logic is not encapsulated in a type, but duplicated for each validation @x:expert-c. Expert D agrees with the poor encapsulation and reusability, and adds that this also affects *C2 Modularity* negatively @x:expert-d.

The function is seen as poorly testable by expert A due to the high number of possible execution paths that need to be covered @x:expert-a. Not only the logic itself, but also the validation of the Dreson itself needs to be tested, resulting in degraded *C6 Testability*.

Finally, the validation logic for the Dreson values suffers from poor *C4 Analysability*, because it is deeply nested and represented through repeated if-conditions and mapping calls @x:expert-b, @x:expert-c, @x:expert-d.

=== Proposed solution

As shown in the previous @usecase2-problems[Chapter], an issue repeatedly mentioned by experts is the current validation of the Dreson input values. For encoding the information that the Dreson is valid in the type system, a newtype can be used. The newtype pattern in Rust is a concept where a tuple struct with a single field is introduced, and a definition can be found in the community-maintained "Rust Unofficial Book" @x:noauthor_introduction_nodate. This way, the original type is wrapped, hiding its functions and enabling new functions to be defined on the wrapper. According to the book, the newtype cannot be confused with the original type, as they are not type compatible, while being a zero-cost abstraction, so it doesn't add runtime cost. Moreover, the newtype pattern is a way of implementing the "Parse, don't validate" principle, as it allows defining a more concrete type with a construction method that only succeeds when the value is valid. Thus, the subsequent lines of code can operate on the newtype and rely on the fact that it must be valid. Thereby, the main issues mentioned for *C7 Faultlessness* are addressed, as invalid states regarding the Dreson cannot exist, and redundant validation is no longer possible.

Introducing a centralized newtype for Dreson values also eliminates code duplication, and allows other handlers to import and use the newtype with the same validation logic, which increases *C3 Reusability*. Moreover, *C6 Testability* is increased, because the validation logic can be tested in isolation, thereby eliminating complicated setup and mocking that were previously required for testing the validation as part of the handler function. The type logic then only needs to be tested once instead of for every handler, an advantage mentioned by expert C while discussing current code smells @x:expert-c.

== Use case 3

The third use case is taken from team Boxfish at OTTO. Boxfish maintains backend services for returned orders, including REST endpoints for retrieving the return status. Some of Boxfish's endpoints are served by AWS Lambdas, which are serverless functions that run in the cloud and are executed on every incoming trigger. The lambda handler called `update_return_status_to_announced` will be analyzed. Because Boxfish hasn't migrated their full codebase to Rust yet, their developers are seeking more concrete coding guidelines and practices for writing idiomatic Rust code.

#figure(
  pad(y: .5cm, image("../res/usecase3/bpmn.png")),
  caption: custom_caption([BPMN process model of the Boxfish Lambda Handler, selected as third use case, which is a sequence of operations that continuously append a shared data structure, read by the final operation],
  [Use Case 3 - BPMN model of Boxfish Lambda Handler])
) <bpmn3>

When a request triggers the lambda handler, the request first gets validated. If it is invalid, the handler directly returns an error. Otherwise, the items transmitted in the request are validated. Besides the valid items, the invalid items are also stored inside an array, depicted as "Failed items" data storage in @bpmn3. If there are no valid items, the following processing steps are skipped and the final response is built, as seen at the long arrow pointing to the merging `XOR`-gate on the right of @bpmn3. In case there are valid items, the return status for each item gets fetched. Again, if there are items that have no return status, they are added to the array of failed items. If the whole request fails, all items are considered as failed and the following steps until the final response building are skipped, jumping to the merging `XOR`-gate in @bpmn3. This is followed by another validation, which validates the return statuses, with invalid items being added to the failed items array. The last processing step is to process the valid items. Similar to the other steps, items that couldn't be processed are added to the failed items array. Lastly, the successful items and all failed items from the array are used to build the final response, which is returned as response to the original request.

=== Relevance

In contrast to use cases 1 and 2, this use case covers all aspects from handling the request, validation, executing business logic, to responding. At team Boxfish, lambdas are a common way of serving endpoints with relatively simple logic, so that no advanced architecture like in the long-running services at FT9 needs to be used. Furthermore, a developer from team Boxfish stated in the expert interview that they are currently building a template for their lambdas, so that a reference example with clean code structure is needed @x:expert-d. This use case will be representative for the *Lambda Handlers* used at Boxfish. 

=== Problems of the status quo <usecase3-problems>

To begin with, the main function owns two mutable vectors `results` and `api_errors`, which are always passed to each function in the processing step as a mutable reference. In Rust, mutable references indicate that a function has side effects. Those side effects decrease *C6 Testability* @x:expert-a, and especially the testing of the whole function gets difficult because the right interactions of these side effects need to be ensured @x:expert-b. Expert D adds that side effects make it harder to verify and test the logic in an isolated manner @x:expert-d. Another indicator for poor testability is the complete absence of any unit tests @x:expert-a.

Furthermore, the shared mutable references are described as unidiomatic in Rust @x:expert-b, @x:expert-c. They make it harder to follow the logic and reason about the state and correctness of the code at any given point @x:expert-b. This is because the passed mutable data needs to be tracked down to understand where it's modified. In addition, expert C expects them to cause errors, for example when concurrency is introduced, and the expert thinks they can be easily replaced by a different approach @x:expert-c. These arguments indicate that runtime behaviour will be unpredictable, which decreases both *C4 Analysability* and *C7 Faultlessness*.

Some of the functions have complex return types, with one of them returning a `Result` wrapped by another `Result`, which is noted negatively by expert a @x:expert-a. This impedes *C4 Analysability*. Another point are functions that accept too generic parameters, for example a whole Request or the whole `ProcessorDependencies` struct, although they only need parts of it. Expert B finds that this obscures what is actually required by the function @x:expert-b, therefore contributing to poor analysability. It has also been identified that it is hard to follow which function can result in what kinds of error cases. Some error cases are only represented implicitly through states like empty arrays, for example.

Another code smell that affects *C4 Analysability* negatively are deeply nested control structures, like loops and if-conditions @x:expert-c. They are especially present in the function that builds the final response, which covers different error cases, making the logic harder to understand @x:expert-c. The code also consists of deep function call hierarchies that are hard to follow, resulting in poor traceability of the control flow @x:expert-d.

It is also noted by an expert that too much logic is concentrated inside a single module @x:expert-a, which signals bad *C2 Modularity*. Confirming this argument, expert C adds that business logic is mixed with technical logic such as @io, which results in a decreased separation of concerns @x:expert-c. Tight coupling additionally decreases *C3 Reusability* @x:expert-d.

Lastly, invalid state is representable in the code because the transitions between the phases are not encoded in the type system and therefore not enforced by the compiler. For example, validation is achieved through a separate function call, but there is no compile-time guarantee that the validation actually happened @x:expert-d. Similar to #link(<usecase1-case-study>, "use case 1"), a change by a developer, like changing the order the functions are called in, might introduce new bugs that stay unnoticed and are only noticed during runtime. This violates the criterion *C7 Faultlessness*. There might also be assumptions about the code not explicitly defined, which might break if changes are made in another code section, resulting in degraded *C5 Modifiability*.

=== Proposed solution <usecase3-solution>

In summary, the main shortcomings of the current code that need to be solved are impure functions with side effects due to shared mutable state, missing separation of concerns like validation, processing and building the result, deep function call hierarchies, implicit states and errors, as well as invariants that are only represented through procedural calls rather than compile-time guarantees.

An architectural design principle that addresses multiple of the named issues is @fcis, which was introduced first by Bernhardt in 2012 @x:bernhardt_functional_2012. The principle aims at applying functional programming for domain logic, which can be encapsulated in pure functions without state or side effects. Their results are predictable and straightforward to unit-test. Everything necessary for interactions with external dependencies, such as handling requests, making database calls or @io is dealt with by the imperative shell, which calls the functional core and is interchangeable. @x:wlaschin_primer_2020, @x:jain_simplify_nodate

Firstly, applying the @fcis principle to this use case would eliminate side effects, addressing issues of *C6 Testability* and *C4 Analysability*. Secondly, it separates different concerns like validation and processing (functional core) from external calls like database calls (imperative shell), which improves *C4 Modularity* and potentially *C2 Reusability* of the functional core. Moreover, it replaces deep function hierarchies with a one-directional functional pipeline and clearly defines the inputs and outputs of each function, enhancing *C5 Analysability*. However, states would still be represented implicitly instead of explicitly through enum variants or result structs, which is compatible with the principle but not required by it. The invariants still wouldn't be enforced, allowing to skip or swap crucial operations, for example.

When using the typestate pattern, which was introduced in @usecase1-solution[Chapter], states are represented through structs that contain the data necessary for each step. The resulting struct from each transition becomes the struct or enum that explicitly encodes the state. Many of the refactoring steps involved when applying @fcis are also compatible with the typestate pattern, such as using pure functions (the state transitions) and replacing deep functional hierarchies with a functional pipeline. But additionally, the typestate pattern enforces invariants, thus making refactorings safer and shifting error detection to compile time, thus addressing *C5 Modifiability* and *C7 Faultlessness*. Thereby, the typestate pattern will be applied, while aiming for pure functions and encoding multiple possible resulting states in the type system in the form of enums.
