#import "../components/formatting.typ": email
#import "../pages/outline.typ": custom_caption

== Digital appendix

Parts of the appendix are not included in the print-out and are available as digital attachments only.

=== Status quo code <status-quo-digi>

Contains the status quo source code of each use case before refactoring.

=== Refactored code <refactored-digi>

Contains the refactored source code of each use case, after the design patterns have been applied.

=== Expert interview transcripts <transcripts-digi>

Contains the original audio files from the interviews, which were conducted in German, and an automatically generated transcript. The transcripts for Experts A, B and D were generated by Microsoft Teams, while the transcript for Expert C was generated by the model OpenAI Whisper.

=== Static code analysis raw results <static-digi>

Contains the raw data calculated by the tool rust-code-analysis.

=== Benchmarking setup <bench-setup-digi>

Contains the source code for configuring the tool Criterion and setting up the test environment and data for each use case's benchmark.

=== Benchmarking raw results <bench-res-digi>

Contains the raw result data and reports generated by the tool Criterion.

== Selected ISO criteria <selected-criteria>

#v(7cm)

#align(
  top,
  block(
    width: 30cm,
    rotate(
      -90deg,
      reflow: false,
      include "appendices/iso_table.typ",
    ),
  ),
)

#pagebreak()

== Correspondence with Crichton via email <email_crichton>

#include "appendices/email_crichton.typ"

== Correspondence with Campbell via email <email_campbell>

#include "appendices/email_campbell.typ"

== Expert interview guideline <expert_questions>
#include "appendices/expert_guide.typ"

== Expert interview summaries <expert_summaries>

=== Expert A
#include "appendices/expert_interview_nico.typ"

=== Expert B
#include "appendices/expert_interview_dirk.typ"

=== Expert C
#include "appendices/expert_interview_falk.typ"

=== Expert D
#include "appendices/expert_interview_fabi.typ"

== Static code analysis

#include "appendices/static_metrics.typ"

== Time behaviour measurement

#include "appendices/time_behaviour.typ"